[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.19.1", default-features = false, features = [ "std" ] }
p256 = { version = "0.13.2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
bincode = "1.3.3"
